### ISSUE TITLE
Allow plotting of both positive and negative values with different colors

### ISSUE THREAD

**Issue by bast** [densities/blob#17]
It would be great to have a cube file tracing an orbital to test/debug this.

**Comment by bast** [comment]
I would appreciate a link to an example cube file. I am working with a relativistic code where it is less trivial to get real valued orbitals.

**Comment by bskinn** [comment]
Ask, and ye shall receive: https://github.com/bskinn/h5cube/blob/70d8d8ccee43a2b0e9ed641bb3e86c95e50be6fe/h5cube/test/resource/grid25mo.cube

It's a rather low-resolution CUBE, but it should be sufficient for testing the +/- coloration.

**Comment by bast** [comment]
Thanks so much! +/- coloration coming up soon.

**Comment by bast** [comment]
The cube file has negative number of centers on line 3 and line 14 was unexpected for me and the parser as well. I have fixed that for my local testing so no problem for my debugging, I was just wondering whether there is anything in the format definition that I am missing.

**Comment by bast** [comment]
The cube file has negative number of centers on line 3 and line 14 was unexpected for me and the parser as well. I have fixed that for my local testing so no problem for my debugging, I was just wondering whether there is anything in the format definition that I am missing.

**Comment by bskinn** [comment]
See [here](https://h5cube-spec.readthedocs.io/en/latest/cubeformat.html). 

The negative value and extra line(s) must be accounted for in parsing...CUBEs can contain more than one dataset (e.g., three, or seven, or twelve different orbitals), and this mechanism is how it's bookkept.

**Comment by bast** [comment]
Thanks a lot Brian - I was indeed unaware of this convention and also did not know this great doc. I will link to it, adjust the parser for this and soon have a working +/- example. Thanks again!

**Comment by bast** [comment]
Parsing has been fixed in 6ccba72e2f9579360fcc5127add0417540f72d03.
